server {
    listen 80;
    server_name budgiefinance.fr www.budgiefinance.fr;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name budgiefinance.fr www.budgiefinance.fr;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    # Toutes les requêtes passent par index.php si le fichier n'existe pas
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Gestion des fichiers PHP
    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    # interdit les fichiers cachés .env, .git, etc.
    location ~ /\. {
        deny all;
    }
}